const $=id=>document.getElementById(id);
const state={master:null,regs:[],stock:null,ssft:null,rows:[],filtered:[]};
const resultCols=['PRDCD','DESC2','ZONA','ALAMAT','DIV','FRAC','ACOST','MINOR','PTAG','QTY','CTN','RUPIAH','SPD','DSI','KEB','KET ZONA','JTD','Over','PKM 0','Hari','KETERANGAN','KET'];
const categoryNames=['Non Dry','Over Stock di toko','PKM Toko 0 (Nol)','Stock kurang dari Minor','Tidak ada JTD Toko','Tidak ada Kebutuhan (PBRO)','Check Fisik WH'];

function setStatus(t){const k={'Siap':'ok','Selesai':'ok','Memproses':'busy','Periksa':'err'}[t]||'';$('status').textContent=t;$('status').className='badge '+k} let zone='a';function msg(t){$(zone==='b'?'messageB':'messageA').textContent=t} function progress(n){$(zone==='b'?'barB':'barA').style.width=Math.max(0,Math.min(100,n))+'%'}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))} function norm(v){return String(v??'').replace(/^\uFEFF/,'').trim()} function num(v){let n=Number(v);return Number.isFinite(n)?n:0}
function ext(n){return String(n||'').toLowerCase().split('.').pop()} function sleep(){return new Promise(r=>setTimeout(r,0))}
function isSpreadsheet(n){return ['xlsx','xls','xlsm','xlsb'].includes(ext(n))}
function detectDelimiter(text){const lines=text.split(/\r?\n/).filter(x=>x.trim()).slice(0,5);const candidates=[',',';','\t','|'];let best=',',score=-1;for(const d of candidates){let n=0;for(const line of lines){let q=false,c=0;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='\"')q=!q;else if(ch===d&&!q)c++;}n+=c;}if(n>score){score=n;best=d}}return best}
function toWb(ab,file){const u=new Uint8Array(ab);if(isSpreadsheet(file.name)||(u[0]===80&&u[1]===75))return XLSX.read(ab,{type:'array',cellDates:true,raw:true});let text=new TextDecoder('utf-8').decode(ab);if(text.charCodeAt(0)===0xFEFF)text=text.slice(1);const delim=detectDelimiter(text);return XLSX.read(text,{type:'string',raw:true,cellDates:true,FS:delim,codepage:65001})}
async function readAny(file){return toWb(await file.arrayBuffer(),file)}
function sheetRows(wb,name){const ws=wb.Sheets[name]||wb.Sheets[wb.SheetNames[0]];return ws?XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true,blankrows:false}):[]}
function findHeader(rows,required,maxScan=15){const req=required.map(x=>x.toUpperCase());for(let i=0;i<Math.min(rows.length,maxScan);i++){const h=(rows[i]||[]).map(x=>norm(x).toUpperCase());if(req.every(k=>h.includes(k)))return {row:i,headers:h}}return {row:0,headers:(rows[0]||[]).map(x=>norm(x).toUpperCase())}}
function hmap(h){const m={};h.forEach((v,i)=>{if(v)m[v]=i});return m}
function parseMaster(rows){let h3=-1,h4=-1;for(let i=0;i<10;i++){const r=(rows[i]||[]).map(x=>norm(x).toUpperCase());if(r.includes('PRDCD')&&r.includes('DESC2'))h3=i;if(r.includes('ST')&&r.includes('ZONA'))h4=i}if(h3<0)throw Error('Master: header PRDCD/DESC2 tidak ditemukan.');const a=hmap((rows[h3]||[]).map(x=>norm(x).toUpperCase())),b=h4>=0?hmap((rows[h4]||[]).map(x=>norm(x).toUpperCase())):{};const map={...a};for(const k of ['ST','ZONA','LT','RAK','BAR','CELL'])if(b[k]!==undefined)map[k]=b[k];const data=[];if(map.LT===undefined)throw Error('Master: kolom LT tidak ditemukan.');const start=Math.max(h3,h4)+2;for(let i=start;i<rows.length;i++){const r=rows[i]||[],id=norm(r[map.PRDCD]);if(!id||norm(r[map.LT])==='')continue;data.push({id,row:r,map})}return data}
function parseStock(rows){const h=findHeader(rows,['PLUKODE','QTY_AKHIR'],8),m=hmap(h.headers),out=new Map();for(let i=h.row+1;i<rows.length;i++){const r=rows[i]||[],id=norm(r[m.PLUKODE]);if(id)out.set(id,r)}return {map:m,rows:out}}
// REG parser supports either a normal single-block PRG or the supplied workbook with 4 horizontal blocks.
function parseRegRows(rows){const out=[];const header=(rows[0]||[]).map(x=>norm(x).toUpperCase());const starts=[];for(let c=0;c<rows[0]?.length;c++)if(norm(rows[0][c]).toUpperCase()==='PRDCD')starts.push(c);if(starts.length>1){for(const start of starts){const trnh=start+97;if(trnh>=rows[0].length||norm(rows[0][trnh]).toUpperCase()!=='TRNH')continue;out.push({rows,start,trnh})}return out}
const h=findHeader(rows,['PRDCD','TRNH'],12),m=hmap(h.headers);if(m.PRDCD===undefined||m.TRNH===undefined){const found=(h.headers||[]).filter(Boolean).slice(0,12).join(', ');throw Error('REG/PRG: PRDCD dan TRNH tidak ditemukan. Format CSV tidak terbaca. Header: '+found)}return [{rows,start:m.PRDCD,trnh:m.TRNH,map:m,row0:h.row}]
}
function monthKey(v){if(v instanceof Date&&!isNaN(v))return `${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,'0')}`;let s=norm(v);if(/^\d{4}$/.test(s)){return `20${s.slice(0,2)}-${s.slice(2)}`}let m=s.match(/(20\d{2})[-\/]?(\d{1,2})/);if(m)return `${m[1]}-${String(m[2]).padStart(2,'0')}`;m=s.match(/(\d{1,2})[-\/]?(20\d{2})/);if(m)return `${m[2]}-${String(m[1]).padStart(2,'0')}`;return s}
function buildRegIndex(regBlocks){const idx=new Map();for(const b of regBlocks){const rows=b.rows;const start=b.start;const trnh=b.trnh;const first=Math.max(1,b.row0?b.row0+1:1);for(let r=first;r<rows.length;r++){const id=norm(rows[r]?.[start]);const mo=monthKey(rows[r]?.[trnh]);if(!id||!mo)continue;if(!idx.has(id))idx.set(id,new Map());idx.get(id).set(mo,{row:rows[r],start})}}return idx}
function stockVal(rec,d){if(!rec)return 0;const c=rec.start+3+(d.getDate()-1)*3;return num(rec.row[c])}
function dateSeries(){const now=new Date();const end=new Date(now.getFullYear(),now.getMonth(),now.getDate()-1);const a=[];for(let i=99;i>=0;i--){const d=new Date(end);d.setDate(end.getDate()-i);a.push(d)}return a}
function daily(id,idx,dates){const mm=idx.get(id);return dates.map(d=>stockVal(mm?.get(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`),d))}
function maxRun(v){const n=v.length,out=Array(n).fill(0);out[n-1]=v[n-1]!==0?1:0;for(let i=n-2;i>=0;i--)out[i]=(out[i+1]===0||v[i]!==v[i+1])?0:out[i+1]+1;return Math.max(...out)}
function unpipe(rows){const sample=rows.slice(0,10).filter(r=>(r||[]).some(x=>norm(x)!==''));const hit=sample.filter(r=>typeof r[0]==='string'&&r[0].includes('|')&&r.slice(1).every(x=>norm(x)==='')).length;if(!sample.length||hit<Math.ceil(sample.length/2))return rows;return rows.map(r=>String((r||[])[0]??'').split('|').map(x=>x.trim()))}
function ssStats(rows){rows=unpipe(rows);const h=findHeader(rows,['PRDCD'],10),m=hmap(h.headers),s=new Map();if(m.PRDCD===undefined)throw Error('SS-FT: header PRDCD tidak ditemukan. Header terbaca: '+h.headers.filter(Boolean).slice(0,12).join(', '));for(let i=h.row+1;i<rows.length;i++){const r=rows[i]||[],id=norm(r[m.PRDCD]);if(!id)continue;if(!s.has(id))s.set(id,{jtd:0,over:0,pkm0:0});const x=s.get(id);x.jtd++;let ket=m.KET!==undefined?norm(r[m.KET]):'';if(!ket){const st=num(r[m.STOCK]),pk=num(r[m.PKM]),mi=num(r[m.MINOR]);ket=pk===0?'PKM 0':(st+mi>pk?'Over':'Kurang')}if(ket==='Over')x.over++;if(ket==='PKM 0')x.pkm0++}return s}
function calc(item,stockRec,regIndex,ss,dates){const r=item.row,m=item.map,id=item.id,get=k=>r[m[k]];const desc=norm(get('DESC2')),zona=get('ZONA'),div=norm(get('DIV')),frac=num(get('FRAC')),acost=num(get('ACOST')),minor=num(get('MINOR')),ptag=norm(get('PTAG')),avg=num(get('AVG')),dsi=num(get('DSISTK')),keb=num(get('KEB'));const vals=daily(id,regIndex,dates),qty=vals[99]||0,stockFinal=stockRec?num(stockRec[2]):'';const hari=maxRun(vals);let keterangan='';if(!['N','R','F'].includes(ptag)&&qty!==0&&hari>=5&&qty!==stockFinal){} else if(!['N','R','F'].includes(ptag)&&qty!==0&&hari>=5&&qty===stockFinal){if(hari>=90)keterangan='Tdk Bergerak >3 Bulan';else if(hari>=60)keterangan='Tdk Bergerak >2 Bulan';else if(hari>30)keterangan='Tdk Bergerak >1 Bulan';else keterangan=`Tdk Bergerak ${hari} Hari`}
// Exact Hasil!V formula: Q-R-S<10 => Over Stock di toko; J<H => Stock kurang dari Minor.
// This ordering is intentional and matches the workbook formula.
// Exact RUMUS HK formula: DE != HM is required for a nonblank KETERANGAN.
if(!keterangan)return null;const st=ss.get(id)||{jtd:0,over:0,pkm0:0};let ket;if((num(zona)===0)&&div==='4')ket='Non Dry';else if(st.jtd===0)ket='Tidak ada JTD Toko';else if(st.pkm0>0)ket='PKM Toko 0 (Nol)';else if(st.jtd-st.over-st.pkm0<10)ket='Over Stock di toko';else if(qty<minor)ket='Stock kurang dari Minor';else if(num(zona)!==0&&keb<10)ket='Tidak ada Kebutuhan (PBRO)';else ket='Check Fisik WH';const ctn=frac?qty/frac:0;return {PRDCD:id,DESC2:desc,ZONA:zona,ALAMAT:norm(get('ALAMAT')),DIV:div,FRAC:frac,ACOST:acost,MINOR:minor,PTAG:ptag,QTY:qty,CTN:ctn,RUPIAH:acost*qty,SPD:avg,DSI:dsi,KEB:keb,'KET ZONA':num(zona)===0?0:(['14','15'].includes(norm(zona))?'Bulky':'Bulky Fraction'),JTD:st.jtd,Over:st.over,'PKM 0':st.pkm0,Hari:hari,KETERANGAN:keterangan,KET:ket}}
async function parseAll(){const bf=$('bahanFile').files[0];if(!bf)throw Error('BAHAN wajib diupload (workbook berisi sheet Master, REG, dan Stock Akhir).');progress(5);const bw=await readAny(bf);progress(30);const pick=(label,test)=>{const f=bw.SheetNames.filter(n=>test(n.toLowerCase().replace(/[^a-z0-9]/g,'')));if(!f.length)throw Error(`BAHAN: sheet ${label} tidak ditemukan. Sheet terbaca: ${bw.SheetNames.join(', ')}`);return f};const master=parseMaster(sheetRows(bw,pick('Master',n=>n==='master')[0]));progress(40);const stock=parseStock(sheetRows(bw,pick('Stock Akhir',n=>n==='stockakhir'||n==='stock')[0]));progress(45);let blocks=[];for(const n of pick('REG',n=>/^(reg|prg)/.test(n))){blocks.push(...parseRegRows(sheetRows(bw,n)));progress(Math.min(55,45+blocks.length*3))}if(blocks.length<4)throw Error(`REG/PRG terdeteksi ${blocks.length} blok. Diperlukan 4 bulan.`);let ss=new Map();if($('ssftFile').files[0]){const ssW=await readAny($('ssftFile').files[0]);ss=ssStats(sheetRows(ssW,'SS-FT'))}return {master,stock,regIndex:buildRegIndex(blocks.slice(0,4)),ss}}
async function process(z){zone=z==='b'?'b':'a';if(zone==='b'&&!$('ssftFile').files[0]){msg('Upload file SS-FT dulu, lalu tekan PROSES.');return}try{setStatus('Memproses');msg('Membaca sumber dan menghitung 100 hari…');progress(0);const {master,stock,regIndex,ss}=await parseAll();const dates=dateSeries();const arr=[];for(let i=0;i<master.length;i++){const x=calc(master[i],stock.rows.get(master[i].id),regIndex,ss,dates);if(x)arr.push(x);if(i%150===0){progress(55+Math.round(i/master.length*40));await sleep()}}state.rows=arr;render(arr);renderKesimpulan();makePrdcdList();progress(100);setStatus('Selesai');if(zone==='a'){$('step3').hidden=true;$('step4').hidden=true;$('step2').hidden=false;msg(`Selesai: ${arr.length} item ditemukan. Lanjut ke langkah 2.`)}else{$('step3').hidden=false;$('step4').hidden=false;msg(`Selesai: ${arr.length} item masuk Hasil.`)}$('exportBtn').disabled=false}catch(e){console.error(e);setStatus('Periksa');progress(0);msg(e.message||String(e))}}
function fmt(c,v){if(v===''||v==null)return '';if(['ACOST','RUPIAH','SPD','DSI'].includes(c))return num(v).toLocaleString('id-ID',{maximumFractionDigits:2});if(['QTY','CTN','FRAC','MINOR','JTD','Over','PKM 0','Hari'].includes(c))return num(v).toLocaleString('id-ID',{maximumFractionDigits:4});return v}
function render(arr){state.filtered=arr;const th=$('resultTable').querySelector('thead'),tb=$('resultTable').querySelector('tbody');th.innerHTML='<tr>'+resultCols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr>';tb.innerHTML=arr.map(r=>'<tr>'+resultCols.map(c=>`<td class="${typeof r[c]==='number'?'num':''}">${esc(fmt(c,r[c]))}</td>`).join('')+'</tr>').join('');$('summary').textContent=`${arr.length.toLocaleString('id-ID')} item • RUPIAH ${arr.reduce((s,r)=>s+num(r.RUPIAH),0).toLocaleString('id-ID')}`}
function renderKesimpulan(){const rows=state.rows;if(!rows.length){$('kesimpulan').textContent='Tidak ada item.';return}const nf=v=>Math.round(v).toLocaleString('en-US');const list=categoryNames.map(n=>{const a=rows.filter(r=>r.KET===n);return {n,c:a.length,rp:Math.round(a.reduce((t,r)=>t+num(r.RUPIAH),0))}}).filter(x=>x.c>0).sort((a,b)=>b.c-a.c);const tgl=new Date().toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'});state.tgl=tgl;const totC=list.reduce((t,x)=>t+x.c,0),totRp=list.reduce((t,x)=>t+x.rp,0);$('kesimpulan').textContent=[`*Checking Item tidak bergerak ${tgl}*`,'','Item  KET | RP',...list.map(x=>`${x.c} Item ${x.n} | Rp ${nf(x.rp)} ,-`),'=================================',`Total | ${totC} Item | Rp ${nf(totRp)} ,-`].join('\n')}
function makePrdcdList(){const ids=[...new Set(state.rows.filter(r=>r.KETERANGAN).map(r=>r.PRDCD))];$('prdcdCount').textContent=ids.length?`${ids.length.toLocaleString('id-ID')} item PRDCD`:'Tidak ada item PRDCD.';$('downloadListBtn').disabled=!ids.length;return ids}
$('downloadListBtn').onclick=()=>{const a=makePrdcdList();const b=new Blob([a.join('\n')+'\n'],{type:'text/plain'}),u=URL.createObjectURL(b),x=document.createElement('a');x.href=u;x.download='PRDCD_SS-FT.txt';x.click();URL.revokeObjectURL(u)};
$('processBtn').onclick=()=>process('a');$('processBtn2').onclick=()=>process('b');$('clearBtn').onclick=()=>location.reload();
$('exportBtn').onclick=()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.rows),'Hasil');const d=categoryNames.map(n=>{const a=state.rows.filter(r=>r.KET===n);return {KET:n,ITEM:a.length,RUPIAH:a.reduce((s,r)=>s+num(r.RUPIAH),0)}});XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d),'Rincian');XLSX.writeFile(wb,`Checking Item tidak bergerak ${state.tgl}.xlsx`)};
$('panduanLink').onclick=()=>{const d=$('panduan');d.showModal?d.showModal():d.setAttribute('open','')};$('panduanClose').onclick=()=>{const d=$('panduan');d.close?d.close():d.removeAttribute('open')};$('panduan').addEventListener('click',e=>{if(e.target===$('panduan'))$('panduanClose').onclick()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
